apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-heqd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yapf-tenant/rhtap-demo-app/hacbs-test-project-heqd@sha256:b77f5f3bab0136c09a9a6c721d733fa253b28fefb65d43294dba576b3a91aa52
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
