apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-heqd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yapf-tenant/rhtap-demo-app/hacbs-test-project-heqd@sha256:30fa60aa14857d984e71b02dc4c045c24a2b13dc2fcfc7da1b1b4d289890a240
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
