apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-heqd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-heqd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-heqd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-heqd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-heqd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yapf-tenant/rhtap-demo-app/hacbs-test-project-heqd@sha256:b77f5f3bab0136c09a9a6c721d733fa253b28fefb65d43294dba576b3a91aa52
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
